[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x44475a"

[colors.dim]
black = "0x14151b"
blue = "0x4d5b86"
cyan = "0x59dffc"
green = "0x1ef956"
magenta = "0xff46b0"
red = "0xff2222"
white = "0xe6e6d1"
yellow = "0xebf85b"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x1b1b1b"
foreground = "0xf8f8f2"

[colors.selection]
background = "0x44475a"
text = "0xf8f8f2"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 17

[font.bold]
family = "mononoki Nerd Font Mono"
style = "Bold"

#[font.debug]
#persistent_logging = false

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
opacity = 1.00

[window.dimensions]
columns = 100
lines = 36

[window.padding]
x = 25
y = 25
